export default {
  SET_STATE: 'setState',
  ADD_ENTITY: 'addEntity',
  REMOVE_ENTITY: 'removeEntity',
  REMOVE_TYPE: 'removeType',
  SET_SCALE: 'setScale',
  SET_FPS: 'setFPS',
  SHOW_LAYER: 'showLayer',
  HIDE_LAYER: 'hideLayer',
  SHOW_OVERLAY: 'showOverlay',
  HIDE_OVERLAY: 'hideOverlay',
  KEY_DOWN: 'keyDown',
  KEY_UP: 'keyUp',
  ENABLE_KEYS: 'enableKeys',
  DISABLE_KEYS: 'disableKeys',
  COLLISION: 'collision',
  CREATE_BODY: 'createBody',
  DESTROY_BODY: 'destroyBody',
  PAUSE_APP: 'pauseApp',
  RESUME_APP: 'resumeApp',
};
