import { Sprite, Stage, AssetLibrary, AssetManifest, Assets } from 'openfl'
import S from './model/stage'
import Game from './game'

class Load extends Sprite {
  init (element) {
    S.windowWidth = window.innerWidth
    S.windowHeight = window.innerHeight
    S.width = S.windowWidth / S.scale
    S.height = S.windowHeight / S.scale

    const manifest = new AssetManifest()

    manifest.addBitmapData('assets/pause.png')
    manifest.addBitmapData('assets/resume.png')
    manifest.addBitmapData('assets/collision/chest.png')
    manifest.addBitmapData('assets/collision/hover.png')
    manifest.addBitmapData('assets/collision/ring.png')
    manifest.addBitmapData('assets/collision/projectile.png')
    manifest.addBitmapData('assets/collision/enemy3.png')
    manifest.addBitmapData('assets/collision/enemy3_death.png')
    manifest.addBitmapData('assets/collision/enemy2.png')
    manifest.addBitmapData('assets/collision/enemy2_death.png')
    manifest.addBitmapData('assets/collision/enemy1.png')
    manifest.addBitmapData('assets/collision/enemy1_death.png')
    manifest.addBitmapData('assets/collision/gubb.png')
    manifest.addBitmapData('assets/collision/enemy.png')
    manifest.addBitmapData('assets/collision/wall.png')
    manifest.addBitmapData('assets/cabin/kettle.png')
    manifest.addBitmapData('assets/cabin/table0.png')
    manifest.addBitmapData('assets/cabin/table1.png')
    manifest.addBitmapData('assets/cabin/table2.png')
    manifest.addBitmapData('assets/cabin/door0.png')
    manifest.addBitmapData('assets/cabin/door1.png')
    manifest.addBitmapData('assets/cabin/door2.png')
    manifest.addBitmapData('assets/cabin/divide.png')
    manifest.addBitmapData('assets/cabin/window0.png')
    manifest.addBitmapData('assets/cabin/kitchen0.png')
    manifest.addBitmapData('assets/cabin/kitchen1.png')
    manifest.addBitmapData('assets/cabin/kitchen2.png')
    manifest.addBitmapData('assets/cabin/kitchen3.png')
    manifest.addBitmapData('assets/cabin/chimney3.png')
    manifest.addBitmapData('assets/cabin/chimney2.png')
    manifest.addBitmapData('assets/cabin/chimney1.png')
    manifest.addBitmapData('assets/cabin/chimney0.png')
    manifest.addBitmapData('assets/cabin/chimney.png')
    manifest.addBitmapData('assets/cabin/bricks0.png')
    manifest.addBitmapData('assets/cabin/bricks1.png')
    manifest.addBitmapData('assets/cabin/bricks2.png')
    manifest.addBitmapData('assets/cabin/ugn.png')
    manifest.addBitmapData('assets/cabin/border.png')
    manifest.addBitmapData('assets/cabin/wall.png')
    manifest.addBitmapData('assets/cabin/wall2.png')
    manifest.addBitmapData('assets/cabin/wall3.png')
    manifest.addBitmapData('assets/cabin/wall4.png')
    manifest.addBitmapData('assets/cabin/floor.png')
    manifest.addBitmapData('assets/forest/logs.png')
    manifest.addBitmapData('assets/forest/bushes.png')
    manifest.addBitmapData('assets/forest/flowers.png')
    manifest.addBitmapData('assets/forest/flowers2.png')
    manifest.addBitmapData('assets/forest/grass.png')
    manifest.addBitmapData('assets/forest/mushrooms.png')
    manifest.addBitmapData('assets/forest/stones.png')
    manifest.addBitmapData('assets/forest/stubs.png')
    manifest.addBitmapData('assets/forest/tree_leaves.png')
    manifest.addBitmapData('assets/forest/tree_stem.png')
    manifest.addBitmapData('assets/forest/twigs.png')
    manifest.addBitmapData('assets/hex/box_colors.png')
    manifest.addBitmapData('assets/hex/j.jpg')
    manifest.addBitmapData('assets/particle.png')
    manifest.addBitmapData('assets/hex/hex_0.png')
    manifest.addBitmapData('assets/hex/hex_1.png')
    manifest.addBitmapData('assets/hex/hex_2.png')
    manifest.addBitmapData('assets/tv/tv_idle.png')
    manifest.addBitmapData('assets/tv/tv_walk.png')
    manifest.addBitmapData('assets/tv/small_missile.png')
    manifest.addBitmapData('assets/owl/owl_walk.png')
    manifest.addBitmapData('assets/owl/owl_idle.png')
    manifest.addBitmapData('assets/owl/owl_shoot.png')
    manifest.addBitmapData('assets/owl/owl_particle.png')
    manifest.addBitmapData('assets/leaf/leaf.png')
    manifest.addBitmapData('assets/leaf/default.png')
    manifest.addBitmapData('assets/leaf/sakura.png')
    manifest.addBitmapData('assets/leaf/rose.png')
    manifest.addBitmapData('assets/grid/btnHighlight.png')
    manifest.addBitmapData('assets/grid/white.png')
    manifest.addBitmapData('assets/grid/dropdown.png')
    manifest.addBitmapData('assets/grid/highlight.png')
    manifest.addBitmapData('assets/grid/border.png')
    manifest.addBitmapData('assets/grid/thin.png')
    manifest.addBitmapData('assets/grid/modal.png')
    manifest.addBitmapData('assets/grid/dark.png')
    manifest.addBitmapData('assets/grid/default.png')
    manifest.addBitmapData('assets/rpg/character/knight.png')
    manifest.addBitmapData('assets/rpg/character/rogue.png')
    manifest.addBitmapData('assets/rpg/character/wizard.png')
    manifest.addBitmapData('assets/caret.png')
    manifest.addBitmapData('assets/handle.png')
    manifest.addBitmapData('assets/transparent.png')
    manifest.addBitmapData('assets/target.png')

    manifest.addFont('04b03', 'assets/font/04b03.ttf')
    manifest.addFont('OldWizard', 'assets/font/OldWizard.ttf')
    manifest.addFont('SNESesque', 'assets/font/SNESesque.ttf')
    manifest.addFont('Akinesia', 'assets/font/Akinesia.ttf')
    manifest.addFont('Anguish', 'assets/font/Anguish.ttf')
    manifest.addFont('Attract', 'assets/font/Attract.ttf')
    manifest.addFont('Awake', 'assets/font/Awake.ttf')
    manifest.addFont('Beggars', 'assets/font/Beggars.ttf')
    manifest.addFont('cadillacs-and-dinosaurs', 'assets/font/cadillacs-and-dinosaurs.ttf')
    manifest.addFont('Coffin', 'assets/font/Coffin.ttf')
    manifest.addFont('Compassion', 'assets/font/Compassion.ttf')
    manifest.addFont('Coulrophobia', 'assets/font/Coulrophobia.ttf')
    manifest.addFont('Dandy', 'assets/font/Dandy.ttf')
    manifest.addFont('Den', 'assets/font/Den.ttf')
    manifest.addFont('Dereliction', 'assets/font/Dereliction.ttf')
    manifest.addFont('DownfallExtended')
    manifest.addFont('Downheartedness')
    manifest.addFont('Eccentric')
    manifest.addFont('Eighties')
    manifest.addFont('Equipment')
    manifest.addFont('EquipmentExtended')
    manifest.addFont('Erosion')
    manifest.addFont('EvenWorse')
    manifest.addFont('Express')
    manifest.addFont('F')
    manifest.addFont('Fortification')
    manifest.addFont('Ghibli')
    manifest.addFont('Hurry')
    manifest.addFont('Improbable')
    manifest.addFont('Ineffective')
    manifest.addFont('Inexpugnable')
    manifest.addFont('Leaflets')
    manifest.addFont('Mantimini')
    manifest.addFont('Marksman')
    manifest.addFont('Nocive')
    manifest.addFont('OldWizard')
    manifest.addFont('Pattern')
    manifest.addFont('Pocket')
    manifest.addFont('Postburn')
    manifest.addFont('Quiver')
    manifest.addFont('Rampike')
    manifest.addFont('Rematch')
    manifest.addFont('Remnant')
    manifest.addFont('Rhyme')
    manifest.addFont('Rings')
    manifest.addFont('Rollback')
    manifest.addFont('Safeguard')
    manifest.addFont('Scherzo')
    manifest.addFont('Shattered')
    manifest.addFont('Sins')
    manifest.addFont('SNESesque')
    manifest.addFont('Suffering')
    manifest.addFont('Targets')
    manifest.addFont('TeatableExtended')
    manifest.addFont('Theoretical')
    manifest.addFont('Trollmini')
    manifest.addFont('Turntable')
    manifest.addFont('Warhorse')
    manifest.addFont('Warpath')
    manifest.addFont('Whatever')
    manifest.addFont('Yellow')
    manifest.addFont('Zankoku')
    manifest.addFont('Zapper')

    AssetLibrary.loadFromManifest(manifest)
      .onComplete((library) => {
        Assets.registerLibrary('default', library)

        const stage = new Stage(
          window.innerWidth,
          window.innerHeight,
          0xbc2733,
          Game
        )
        element.replaceWith(stage.element)
      })
      .onError((e) => {
        console.error(e)
      })
  }
}

export default Load;
